### ISSUE TITLE
FindAuthorizationsByUserNameAsync returns all users

### ISSUE THREAD

**Issue by stmax82** [influxdata/influxdb-client-csharp#199]
`FindAuthorizationsByUserNameAsync("myuser")` should only return authorizations for the specified user, but instead returns all authorizations.

The following should return authorizations for user "myuser" only:

```fsharp
let auths =
    influx
        .GetAuthorizationsApi()
        .FindAuthorizationsByUserNameAsync("myuser")
    |> Async.AwaitTask
    |> Async.RunSynchronously

for auth in auths do
    printfn $"{auth.User}"
```

But it outputs:

```
admin
myuser
```

Similar FindAuthorizationsByUser* functions might have the same problem (not tested).

Tested with InfluxDB.Client 1.18.

**Comment by bednar** [comment]
Hi @stmax82,

The `FindAuthorizationsByUserNameAsync()` is just wrapper for InfluxDB API: [/api/v2/authorizations](https://docs.influxdata.com/influxdb/cloud/api/#operation/GetAuthorizations). 


I've test the InfluxDB API by:
```console
curl -i -X GET 'http://localhost:8086/api/v2/authorizations&user=my-user' -H 'Authorization: Token my-token'
```

and results are incorrect. 

This issue is related to server implementation. Can you please move this issue into http://github.com/influxdata/influxdb repository?

Regards

**Comment by bednar** [comment]
This issue has been closed because it is related to server implementation.
