### ISSUE TITLE
Feature request (linq): when using Take (or TakeLast), use limit() (or tail) before pivot()

### ISSUE THREAD

**Issue by amitrotner** [influxdata/influxdb-client-csharp#318]
Proposed Changes
When using Take or TakeLast operators, translate the query to Flux such as limit() and tail() will be before pivot() to achieve better performance.

A simple experiment conducted locally (see the time difference):

Limit():
Before:
![image](https://user-images.githubusercontent.com/42109793/166149916-895b17de-a53a-451b-a5fe-3bb4a1f686ee.png)
After:
![image](https://user-images.githubusercontent.com/42109793/166149933-33a0a542-9b3c-4ccb-b84c-3ee4122d17be.png)

Tail():
Before:
![image](https://user-images.githubusercontent.com/42109793/166149692-09915638-6074-4f78-8659-bf35c7565b7e.png)

After:
![image](https://user-images.githubusercontent.com/42109793/166149731-0320bc0d-1e05-4531-962f-89d7de95798b.png)

**Comment by bednar** [comment]
Hi @amitrotner,

thanks for using our client and your suggestion.

Unfortunately we can't do this optimisation as a default behaviour because it doesn't works for all cases. Check out this:

##### Data

```
m1 f1=1,f2=2 1
m1 f1=3,f2=4 2
m1 f1=5,f2=6 3
m1 f1=7,f2=8 4
m1 f1=9,f2=10,f3=11 5
m1 f1=12,f2=13,f3=14 6
m1 f1=15,f2=16,f3=17 7
m1 f1=18,f2=19,f3=20 8
```

##### Query: `select *` 

```
from(bucket: "my-bucket") 
	|> range(start: 0)
	|> drop(columns: ["_start", "_stop", "_measurement"])
	|> pivot(rowKey:["_time"], columnKey: ["_field"], valueColumn: "_value")
```

![image](https://user-images.githubusercontent.com/455137/166194672-4dbe6187-a0f0-413f-99fb-92eceba2dce9.png)

##### Query: `select * limit 2` 

```
from(bucket: "my-bucket") 
	|> range(start: 0)
	|> drop(columns: ["_start", "_stop", "_measurement"])
	|> pivot(rowKey:["_time"], columnKey: ["_field"], valueColumn: "_value")
	|> limit(n: 2) 
```

![image](https://user-images.githubusercontent.com/455137/166194757-47494db6-b64b-4d4c-986b-aebd4bc10116.png)

But if we move `limit` before `drop` than the results are inconsistent:

```
from(bucket: "my-bucket") 
	|> range(start: 0)
	|> limit(n: 2) 
	|> drop(columns: ["_start", "_stop", "_measurement"])
	|> pivot(rowKey:["_time"], columnKey: ["_field"], valueColumn: "_value")
```

![image](https://user-images.githubusercontent.com/455137/166194844-3a3969b8-6ca9-4214-a365-a003d44118a6.png)

What do you think about a new option in `QueryableOptimizerSettings`?

Regards

**Comment by amitrotner** [comment]
@bednar 
Thanks for your reply.

I see the problem of using my suggestion in this case.
I think a new option in `QueryableOptimizerSettings` will be good too.

Thanks!
