### ISSUE TITLE
CSV export and import

### ISSUE THREAD

**Issue by jwillmer** [influxdata/influxdb-client-csharp#651]
I am using the REST API Query endpoint to get all data from a bucket in my .NET app. I don't use the .NET SDK to ensure I get the raw data without any modifications:

```c#
var fluxQuery = $"from(bucket: \"{_edgeSettings.MetricSettings.BucketName}\") |> range(start: {startTime})";
var query = new
{
    query = fluxQuery,
    type = "flux",
    dialect = new
    {
        annotations = new[] { "group", "datatype", "default" }
    }
};

var jsonQuery = Newtonsoft.Json.JsonConvert.SerializeObject(query);
var content = new StringContent(jsonQuery);
content.Headers.ContentType = new MediaTypeHeaderValue("application/json");

var response = await client.PostAsync($"{_edgeSettings.MetricSettings.InfluxDbUrl}/api/v2/query?org={_edgeSettings.MetricSettings.Organization}", content);
var data = await response.Content.ReadAsStringAsync();
```

I then sync it from my edge location to the cloud and try to import it to the influxdb in the cloud. (We need to take control of the sync between edge and cloud and can't use build in tooling).

```c#
var url = $"{_cloudSettings.MetricSettings.InfluxDbUrl}/api/v2/write?" +
    $"org={_cloudSettings.MetricSettings.Organization}" +
    $"&bucket={_cloudSettings.MetricSettings.BucketName}" +
    "&precision=s";
var content = new StringContent(data, Encoding.UTF8, "text/plain");
var response = await client.PostAsync(url, content);
```

But the cloud endpoint complains about invalid syntax in the data. I also tried it with query endpoint with similar success. Note that I also played around with gzip the content but I could not get it work.

```c#
var escapedData = $"import \"csv\"\n csv.from(csv: \"{data}\")\n |> to(bucket: \"metrics\")";
escapedData = JsonConvert.SerializeObject(escapedData);
jsonQuery = $"{{ \"query\": {escapedData} }}";

content = new StringContent(jsonQuery, Encoding.UTF8, "application/json");
content.Headers.ContentType = new MediaTypeHeaderValue("application/json");

var request = new HttpRequestMessage
{
    Method = HttpMethod.Post,
    RequestUri = new Uri($"{_cloudSettings.MetricSettings.InfluxDbUrl}/api/v2/query?org={_cloudSettings.MetricSettings.Organization}"),
    Content = content
};
request.Headers.AcceptEncoding.Add(new StringWithQualityHeaderValue("gzip"));

response = await client.SendAsync(request);
```

I'm now completely stuck in synchronizing the data. Any help, hint or example would be much appreciated.

**Comment by bednar** [comment]
Hi @jwillmer,

Thank you for using our client and for reaching out.

Based on the information you've provided, it seems there might be an issue or oversight with how the queried data is being processed after retrieval. In order to effectively write back to InfluxDB or manipulate the data further, it's crucial to ensure that your data is correctly transformed into the appropriate format, specifically the Line Protocol format used by InfluxDB.

Could you please confirm whether you are transforming your queried data into Line Protocol? The transformation process is essential for ensuring that the data can be efficiently ingested back into InfluxDB or processed further according to your requirements.

Here's a quick guide on how to transform your data into Line Protocol:

1. **Structure Your Data**: Ensure each data point has a measurement, field set, optional tag set, and a timestamp.
2. **Format Correctly**: Follow the Line Protocol format: `measurement,tag1=value1,tag2=value2 field1="value1",field2=value2 timestamp`.

Looking forward to hearing from you.

Best Regards.

**Comment by jwillmer** [comment]
I did a workaround. I used Telegraf API to get the data pushed to my API endpoint as line protocol. Then I can use it to import it to InfluxDB. It is just very annoying that I have to manually modify the data format in order to do an export -> import action on InfluxDB.

Sadly, my workaround prevents me from aggregating the data before sending. But I don't want to maintain the transformation logic. Could your C# client not expose the transformation logic? I think I saw it in your internals once.

**Comment by bednar** [comment]
For this task, the optimal approach is to query data into a DataClass and then write this DataClass back to InfluxDB. For more details, please see the following resources:

- [Querying into DataClass](https://influxdata.github.io/influxdb-client-csharp/api/InfluxDB.Client.QueryApi.html#InfluxDB_Client_QueryApi_QueryAsyncEnumerable__1_System_String_System_String_CancellationToken_)
- [Writing from DataClass](https://influxdata.github.io/influxdb-client-csharp/api/InfluxDB.Client.WriteApiAsync.html#InfluxDB_Client_WriteApiAsync_WriteMeasurementsAsync__1_List___0__InfluxDB_Client_Api_Domain_WritePrecision_System_String_System_String_CancellationToken_)
- [PocoQueryWriteExample on GitHub](https://github.com/influxdata/influxdb-client-csharp/blob/master/Examples/PocoQueryWriteExample.cs)
