### ISSUE TITLE
Contribution offer

### ISSUE THREAD

**Issue by bnayae** [influxdata/influxdb-client-csharp#93]
I would like to contribute the following functionality.

- PointData.Tags: will accept IReadOnlyDictionary
- Immutable PointData builder
  currently PointData cannot be reuse because it Mutable.
  Therefore the following scenario will have side effect:

`
// may be register with DI as initial state
var pointBase = PointData
    .Measurement("xyz")
    .Tag("company", "best-one")
    .Tag("feature", "a");
`

`
var point = pointBase.Field("count", 10);
using (var writeApi = _client.GetWriteApi())
{
    writeApi.WritePoint(BUCKET, TENANT, point);
}
`

`
var point = pointBase.Tag("path", "/api")
                        .Field("count", 10);
using (var writeApi = _client.GetWriteApi())
{
    writeApi.WritePoint(BUCKET, TENANT, point);
}
`

What's your opinion?

**Comment by bednar** [comment]
Hi @bnayae,

thanks for using our client. 

If you would like to have a default tags for your `DataPoint` you could use **default tags**. Something like:

```csharp
var BUCKET = "my-bucket";
var TENANT = "my-org";

var options = new InfluxDBClientOptions.Builder().Url("http://localhost:9999")
    .AuthenticateToken("my-token".ToCharArray())
    .Org(TENANT)
    .Bucket(BUCKET)
    .AddDefaultTag("company", "best-one")
    .AddDefaultTag("feature", "a")
    .Build();

var _client = InfluxDBClientFactory.Create(options);

var point = PointData.Measurement("xyz").Field("count", 10);
using (var writeApi = _client.GetWriteApi())
{
    writeApi.WritePoint(point);
}
```

- https://github.com/influxdata/influxdb-client-csharp/tree/master/Client#default-tags

BTW, all PRs are welcome and Immutable PointData builder sounds good 👍 

Regards

**Comment by bnayae** [comment]
Default Tags works for me.
I will check the immutability and offer pull request.
Thanks for the response.

**Comment by bednar** [comment]
Thanks. 

I'm looking forward to your PR.

**Comment by bnayae** [comment]
Will it be fine to split the PointData into different nuget (project) i.e. InfluxDB.Contracts?

The reason I'm asking is for being enable to abstract InfluxDBClient for different specialized interfaces like Metrics vs. Business data,
and inject those specialized contract via DI.

The specialized contract may look like (not part of your code base):
`
interface ICommonTimeSeriesWriter
{
   void WritePoint(PointData point);
}
interface IMetrics: ICommonTimeSeriesWriter {}
interface IBusiness: ICommonTimeSeriesWriter {}
`

Splitting NuGets will be friendlier for the consumer which won't need to reference the implementation (only the data portion).

**Comment by bednar** [comment]
Currently we already have three nuget packages:

- `InfluxDB.Client.Core` - exceptions, validations, REST client
- `InfluxDB.Client` - client that allows query, write and management (bucket, organization, users) for the InfluxDB 2.0
- `InfluxDB.Client.Flux` - client that allow perform Flux Query against the InfluxDB 1.7+

The `InfluxDB.Client.Core` could be a good place to add contracts like `ICommonTimeSeriesWriter` and `PointData`.

**Comment by jaredwri** [comment]
I have a few questions/concerns with the `InfluxDB.Client` package.
1. Why the need to support `IDisposable` for what should be a stateless client?  
2. What is the recommanded lifetime of an `InfluxDbClient` object?  Consider I'm publishing data in conjunction with web requests from my application.  If I wire in the client using DI and register as a **singleton**, one instance for the application for the duration of it's lifetime.   Will that cause a detriment to the state of the client?  Will resources owned by my instance *time-out*?  If I used username/password **is** the session duration infinate?  If not will I end up holding a reference to an `InfluxDBClient` instance that just doesn't work any more because of implementation details?
3. This is small and somewhat nit-picky, but, some of the interactions expose un-necessary implementation choices to the developer/consumer.   An example is token is a `char[]`, why not just push that knowledge into the implemenatation and just expose token as a `string`?  Then, in the deep internals, you can call `token.ToCharArray()` if that is what you prefer.
4. `Async`/`await` support is missing.
5. Why does the write api use batching?  Is it not ok to just send a single point at the time I invoke the api?
6. Why not break the `line protocol/models` into a separate nuget it seems to be the one thing that we need if I decide to use the raw api?
7. All of the builder methods actually complicate what is required by a given *thing*.   

for instance to invoke the write api I *may* start with configuring my options as follows:
```csharp
var options = InfluxDBClientOptions.Builder
                .CreateNew()
                .Bucket("bucket")
                .AuthenticateToken("token-should-be-a-string".ToCharArray())
                .Build();

            var client= InfluxDBClientFactory.Create(options);
            
// eventually the local _options is set and lazy consumed by sub-api's
protected internal InfluxDBClient(InfluxDBClientOptions options)
    {
      Arguments.CheckNotNull((object) options, nameof (options));
      this._options = options;
    ...
 public WriteApi GetWriteApi(WriteOptions writeOptions)
    {
      WriteApi writeApi = new WriteApi(this._options, new WriteService((Configuration) this._apiClient.Configuration)
      ...
 protected internal WriteApi(
      InfluxDBClientOptions options,
      WriteService service,
      WriteOptions writeOptions,
      InfluxDBClient influxDbClient)
    {
      WriteApi writeApi = this;
      Arguments.CheckNotNull((object) service, nameof (service));
      Arguments.CheckNotNull((object) writeOptions, nameof (writeOptions));
      Arguments.CheckNotNull((object) influxDbClient, nameof (_influxDbClient));
      this._options = options;  
      ...
    // here the error will manifest itself in the form of a null reference exception since i didn't set the org value
    public void WritePoint(PointData point)
    {
      this.WritePoint(this._options.Bucket, this._options.Org, point);
    }
```
I guess the point I'm trying to make is the **ctor** for a given thing, or the **method** being invoked, really dictates what is required, why not just expose that to me instead of the levels of indirection that cause me to pull the repo down to see what i've missed in configuration?   

I'm clearly not understaning your use cases. With that being said I also think that my use cases have been complicated to the point that I'm not sure how to properly use them.

**Comment by bednar** [comment]
Hi @jaredwri,

thanks for your comments and suggestions.

1. It's because we have to flush a write buffer.
2. The `InfluxDBClient` could be a singleton and be disposed when you destroy your DI environment. The username / password session is not infinite (see doc - https://v2.docs.influxdata.com/v2.0/reference/config-options/#session-length) - preferred way is to use a token.
3. Yeah, `char []` is not ideal. What do you think about a [securestring] (https://docs.microsoft.com/en-us/dotnet/api/system.security.securestring?view=netcore-3.1)?
4. This is a second request to simple `Async / await` write. We will prepare it stay tuned at # 23.
5. It's due to performance optimization.
6. What exactly will be in a new nuget package?
a. [InfluxDB.Client.Core.Flux.Domain *] (https://github.com/influxdata/influxdb-client-csharp/tree/master/Client.Core/Flux/Domain)
b. [InfluxDB.Client.Api.Domain *] (https://github.com/influxdata/influxdb-client-csharp/tree/master/Client/InfluxDB.Client.Api/Domain)
7. I think a builder method is self-documented and allows use a client without extra effort. The second benefit is that it allows us to refactor a code without breaking existing user code (eg create new `WriteApiAsyncAwait`).

Regards

**Comment by jaredwri** [comment]
Hi @bednar,

Thanks for the response and sorry in advance for the novel.  I don't mean to critique especially with someones open source efforts.   What is your threshold for change on this, is this project open to introducing breaking changes?

1/5. Do we really need a buffer on the client?  Shouldn't that be a decision made by the consumer of the client library.  Is that the standard use case?  Couldn't that be its own thing with a separate responsibility?   For instance a BufferedWriteOperation that is the unit of "Disposability".  Below is a pseudo code as an example working under the assumption that the `InfluxDBClient` has already been created.  In my use case my measurements don't stack very often and if I require a guarantee I would use a pub/sub like rabbitmq to ensure I don't lose any data.

```csharp
public class BufferedWriteOperation : IDisposable
{
    // Observable stuff moved here
    public void WriteRecord(string bucket, string org, WritePrecision precision, string record) {...}
    public async Task WriteRecord(string bucket, string org, WritePrecision precision, string record, CancellationToken cancellationToken) {...}
}

public InfluxDBClient Client { get; }
public void ConsumingCode()
{
	using var buffer = Client.GetBufferedWriter();
	buffer.WriteRecords("bucket", "org", precision, records);
	buffer.Flush();
}
public Task ConsumingCodeAsync()
{
	using var buffer = Client.GetBufferedWriter();
	await buffer.WriteRecordsAsync("bucket", "org", precision, records, CancellationToken.None);
}
```

3. Devleopers are pretty used to securing their own configuration these days you should just let them make a decision on what they feel they need to secure and how they want to secure it.   To support this, imagine if RestSharp forced you do provide a `SecureString` or even worse, a custom construct.   You'd be forced to create a bunch of adapter code or bleed that design decision up to the caller/consumer.   It may be best to just acknowledge that a token is a string and the value/security around that is not the clients concern.  

4. Looking forward to that.

6. So this isn't 100% necessary if a Client.Core nuget exposed a simple HttpClient implmentation of interacting with the api.  In my case I wanted to *avoid* using the `WriteApi` and just use the rest api due to it's complexity.   I personally would focus on the models/classes that were in play in order to read/write data from the api.
- From the write side things like: Atrributes, PointData, MeasurementMapper (public with interface) and/or the notion of a LineProtocolSerializer.    

7. The builder method only documents the available options and not *how* one or more options are used in conjunction with each other.  When are the options asserted for validity of usage?

```csharp
    // What is my expectation if I do this?
    var options = InfluxDBClientOptions.Builder.CreateNew()
                .Authenticate("user", "password".ToCharArray())
                .AuthenticateToken("token".ToCharArray())
                .Build(); 
    // now this...will it use the same auth scheme as above.  what takes precedence? I know because I looked at the code, but is your goal to get me to understand by interrogating the source?
     var options = InfluxDBClientOptions.Builder.CreateNew()
                .AuthenticateToken("token".ToCharArray())
                .Authenticate("user", "password".ToCharArray())
                .Build();
                
    
```
Using a ctor (or static creators that forced a signature) you can both enforce the parameter set and the usage at the same time. If any required parameter is missing it's an exception and at the same time setting the expectation on how we are communicating with the api.
```csharp
    // Implied that token auth will be used 
    public InfluxDBClientOptions (string url, string org, string token) { }
    // Implied that username/password basic auth will be used. 
    public InfluxDBClientOptions (string url, string org, string username, string password) { }
    
    // or 
    public static InfluxDBClientOptions CreateNew(string url, string org, string username, string password) 
    {
        // validate and assert all values.
        return CreateNew().Url(url).Org(org).Authenticate(user, password).Build();
    }
    
```

**Comment by bednar** [comment]
Hi @jaredwri,

1/5. Yes. There are users that wants to write a lot of data without extra coding.

3. The `RestSharp` doesn't force us to use a `SecureString` but we have to keep a confidential token and password in memory.  

7. It is simple... latest win. The builder method also allow to us prepare helpers something like:

https://github.com/influxdata/influxdb-client-csharp/blob/0beb2048ad393636907c50fcf7d3389c53f61a81/Client/InfluxDBClientFactory.cs#L85

**Comment by bednar** [comment]
@bnayae I am very thankful for yours help with client. Thanks.

The `jitter-interval` is primarily to avoid large write spikes for users running a large number of client instances. ie, a jitter of 5s and `flush-interval` 10s means flushes will happen every 10-15s.
 
InfluxDB clients could be deployed on many hosts and these hosts could be started at once. When this happens and all of them have values to write (it is even worse when they have to write data that were buffered while the clients were down) it easily happens that InfluxDB server gets overloaded because the instance wasn't scaled for such spike in load.
